-- Prompt 12 — viewer accounts.
--
-- Hand-authored: no database is reachable from the build container, so this was
-- not generated by `prisma migrate dev`. Statement order and naming follow the
-- conventions in 20260811045641_init. Run `prisma migrate status` against a real
-- database before deploying, and `prisma migrate diff` to confirm it lands the
-- schema exactly.
--
-- Three groups of change:
--   1. auth_tokens         — new; password reset and email verification
--   2. consent_records     — new `granted` column, so a withdrawal is expressible
--   3. drift from Prompts 04 and 07 — three columns that reached schema.prisma
--      but never a migration

-- CreateEnum
CREATE TYPE "AuthTokenPurpose" AS ENUM ('password_reset', 'email_verification');

-- CreateTable
CREATE TABLE "auth_tokens" (
    "id" SERIAL NOT NULL,
    "user_id" INTEGER NOT NULL,
    "token_hash" VARCHAR(64) NOT NULL,
    "purpose" "AuthTokenPurpose" NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "consumed_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_tokens_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "auth_tokens_token_hash_key" ON "auth_tokens"("token_hash");

-- CreateIndex
CREATE INDEX "auth_tokens_user_id_idx" ON "auth_tokens"("user_id");

-- CreateIndex
CREATE INDEX "auth_tokens_token_hash_idx" ON "auth_tokens"("token_hash");

-- AlterTable
-- Existing rows all represent an acceptance, so the default backfills correctly.
ALTER TABLE "consent_records" ADD COLUMN "granted" BOOLEAN NOT NULL DEFAULT true;

-- AlterTable
-- Drift from Prompt 04 (course JSON columns) and Prompt 07 (subscription
-- cancellation). Nullable, so no backfill is required.
ALTER TABLE "content_items" ADD COLUMN "outcomes_json" TEXT;
ALTER TABLE "content_items" ADD COLUMN "cert_config_json" TEXT;
ALTER TABLE "subscriptions" ADD COLUMN "cancelled_at" TIMESTAMP(3);
